In [2]:
import pandas as pd

In [8]:
dados_epe = pd.read_excel(
    io = '/content/Matriz ab2021.xlsx',
    header = [2,3,4]
)
dados_epe

                                                 FLUXO      PETRÓ_  GÁS NAT.  \
                                                BRASIL         LEO     ÚMIDO
                                    Unnamed: 0_level_2      mil m3   milh m3
0                                             PRODUÇÃO  168783.516  48818.75
1                                           IMPORTAÇÃO    8133.621         0
2                                 VARIAÇÃO DE ESTOQUES    -345.976         0
3                       OFERTA TOTAL                    176571.161  48818.75
4                                           EXPORTAÇÃO  -72640.239         0
..                                                 ...         ...       ...
242                            CARVÃO MINERAL & OUTROS           0         0
243                             CONSUMO NÃO ENERGÉTICO           0         0
244                           MATÉRIA PRIMA DA QUÍMICA           0         0
245                                       OUTROS USOS            0         0
246  OBS: o total de náfta processado pela indústri...         NaN       NaN

                C.VAPOR                                               \
           SECO    3100        3300     3700       4200         4500
        milh m3   mil t       mil t    mil t      mil t        mil t
0             0       0  1890.39086  6.13414  72.306755  3986.814046
1       16855.7       0           0        0          0            0
2           200       0         270        0          0          300
3       17055.7       0  2160.39086  6.13414  72.306755  4286.814046
4             0       0           0        0          0            0
..          ...     ...         ...      ...        ...          ...
242           0       0           0        0          0            0
243  3100.41227       0           0        0          0            0
244  3100.41227       0           0        0          0            0
245           0       0           0        0          0            0
246         NaN     NaN         NaN      NaN        NaN          NaN

                 ...              Biogás            Biomassa  \
           4700  ... Unnamed: 58_level_1 Unnamed: 59_level_1
          mil t  ...             mil tep             mil tep
0    414.861541  ...          375.735723         1188.737682
1          89.8  ...                 NaN                 NaN
2             0  ...                 NaN                 NaN
3    504.661541  ...          375.735723         1188.737682
4             0  ...                 NaN                 NaN
..          ...  ...                 ...                 ...
242           0  ...                   0                   0
243           0  ...                   0                   0
244           0  ...                   0                   0
245           0  ...                   0                   0
246         NaN  ...                 NaN                 NaN

         Óleos Vegetais                                   Total  \
    Unnamed: 60_level_1 Unnamed: 61_level_1 Unnamed: 62_level_1
                mil tep             mil tep             mil tep
0           5584.339783                 NaN         1828.792544
1                   NaN                 NaN                   0
2                     0                 NaN                   0
3           5584.339783                 NaN         1828.792544
4                   NaN                 NaN                   0
..                  ...                 ...                 ...
242                   0                 NaN                   0
243                   0                 NaN                   0
244                   0                 NaN                   0
245                   0                 NaN                   0
246                 NaN                 NaN                 NaN

                    LGN Gás de alto forno coque carvão      Gás de aciaria  \
    Unnamed: 63_level_1            Unnamed: 64_level_1 Unnamed: 65_level_1
                mil tep                        mil tep             mil tep
0                     0                    1177.666673            48.86667
1                   NaN                            NaN                 NaN
2                   NaN                            NaN                 NaN
3                     0                    1177.666673            48.86667
4                   NaN                            NaN                 NaN
..                  ...                            ...                 ...
242                   0                              0                   0
243                   0                              0                   0
244                   0                              0                   0
245                   0                              0                   0
246                 NaN                            NaN                 NaN

    Gás de enxofre e  outros      Outras ñ renov
         Unnamed: 66_level_1 Unnamed: 67_level_1
                     mil tep             mil tep
0                 321.409469          280.849732
1                        NaN                 NaN
2                        NaN                 NaN
3                 321.409469          280.849732
4                        NaN                 NaN
..                       ...                 ...
242                        0                   0
243                        0                   0
244                        0                   0
245                        0                   0
246                      NaN                 NaN

[247 rows x 68 columns]

In [19]:
dados_epe.sample(6)

                              FLUXO PETRÓ_ GÁS NAT.             C.VAPOR        \
                             BRASIL    LEO    ÚMIDO        SECO    3100  3300
                 Unnamed: 0_level_2 mil m3  milh m3     milh m3   mil t mil t
168                          TÊXTIL      0        0  179.523862       0     0
73                          QUÍMICA      0        0  463.583214       0     0
143  CARVOARIAS                          0        0           0       0     0
202                          TÊXTIL      0        0    3.263589       0     0
163                     FERRO LIGAS      0        0    2.921673       0     0
5                   NÃO APROVEITADA      0    -1200       -33.7       0     0

                                 ...              Biogás            Biomassa  \
     3700  4200  4500      4700  ... Unnamed: 58_level_1 Unnamed: 59_level_1
    mil t mil t mil t     mil t  ...             mil tep             mil tep
168     0     0     0         0  ...                   0                   0
73      0     0     0  0.993679  ...                   0           18.038757
143     0     0     0         0  ...                   0                   0
202     0     0     0         0  ...                   0                   0
163     0     0     0         0  ...                   0                   0
5       0     0     0         0  ...                 NaN                 NaN

         Óleos Vegetais                                   Total  \
    Unnamed: 60_level_1 Unnamed: 61_level_1 Unnamed: 62_level_1
                mil tep             mil tep             mil tep
168                   0                 NaN                   0
73                  NaN                 NaN          246.776618
143                   0                 NaN                   0
202                   0                 NaN                   0
163                   0                 NaN                   0
5                   NaN                 NaN                   0

                    LGN Gás de alto forno coque carvão      Gás de aciaria  \
    Unnamed: 63_level_1            Unnamed: 64_level_1 Unnamed: 65_level_1
                mil tep                        mil tep             mil tep
168                   0                              0                   0
73                  NaN                              0                   0
143                   0                              0                   0
202                   0                              0                   0
163                   0                              0                   0
5                   NaN                            NaN                 NaN

    Gás de enxofre e  outros      Outras ñ renov
         Unnamed: 66_level_1 Unnamed: 67_level_1
                     mil tep             mil tep
168                        0                   0
73                246.776618                 NaN
143                        0                   0
202                        0                   0
163                        0                   0
5                        NaN                 NaN

[6 rows x 68 columns]

In [17]:
dados_aneel = pd.read_csv(
    filepath_or_buffer = '/content/siga-empreendimentos-geracao.csv',
    encoding = "ISO-8859-1", sep=';',
    on_bad_lines='skip',
    header = [0]
)
dados_aneel

,DatGeracaoConjuntoDados,NomEmpreendimento,IdeNucleoCEG,CodCEG,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DscFonteCombustivel,DscTipoOutorga,...,MdaPotenciaFiscalizadaKw,MdaGarantiaFisicaKw,IdcGeracaoQualificada,NumCoordNEmpreendimento,NumCoordEEmpreendimento,DatInicioVigencia,DatFimVigencia,DscPropriRegimePariticipacao,DscSubBacia,DscMuninicpios
0,2022-11-01,E,8,PCH.PH.MG.000008-6.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1400,",00",Não,"-20,12479858","-43,87020250",2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI Cï¿½RREGO DO Sï¿½T...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
1,2022-11-01,F,9,PCH.PH.MG.000009-4.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,3972,",00",Não,"-20,13187300","-43,87693500",2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI Cï¿½RREGO DO Sï¿½T...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
2,2022-11-01,G,10,PCH.PH.MG.000010-8.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1440,",00",Não,"-20,13754468","-43,89192620",2000-08-31,2030-08-31,100% para ANGLOGOLD ASHANTI Cï¿½RREGO DO Sï¿½T...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
3,2022-11-01,14 de Julho,12,UHE.PH.RS.000012-4.1,RS,UHE,Operação,Hídrica,Potencial hidráulico,Concessão,...,100000,"47500,00",Não,"-29,06475278","-51,67494167",2001-03-15,2039-11-13,100% para COMPANHIA ENERGï¿½TICA RIO DAS ANTAS...,86 - Taquari,"Bento Gonçalves - RS, Cotiporã - RS"
4,2022-11-01,Abaúna,15,CGH.PH.RS.000015-9.1,RS,CGH,Operação,Hídrica,Potencial hidráulico,Registro,...,720,"510,00",Não,"-27,82377500","-52,06999722",NaN,NaN,100% para Cooperativa de Geraï¿½ï¿½o de Energi...,"72 - Uruguai, Inhanduva, Peixe e outros",Floriano Peixoto - RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23078,2022-11-01,10546,70676,UFV.RS.MS.070676-0.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,",00000000",",00000000",NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
23079,2022-11-01,10547,70677,UFV.RS.MS.070677-9.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,",00000000",",00000000",NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
23080,2022-11-01,10548,70678,UFV.RS.MS.070678-7.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,",00000000",",00000000",NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
23081,2022-11-01,10549,70679,UFV.RS.MS.070679-5.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,",00000000",",00000000",NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS
23082,2022-11-01,10544,70680,UFV.RS.MS.070680-9.1,MS,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,",00000000",",00000000",NaN,NaN,100% para ENERGISA MATO GROSSO DO SUL - DISTRI...,NaN,Corumbá - MS

In [18]:
dados_aneel.sample(6)

,DatGeracaoConjuntoDados,NomEmpreendimento,IdeNucleoCEG,CodCEG,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DscFonteCombustivel,DscTipoOutorga,...,MdaPotenciaFiscalizadaKw,MdaGarantiaFisicaKw,IdcGeracaoQualificada,NumCoordNEmpreendimento,NumCoordEEmpreendimento,DatInicioVigencia,DatFimVigencia,DscPropriRegimePariticipacao,DscSubBacia,DscMuninicpios
15200,2022-11-01,Ataide Almeida de Freitas,60812,UFV.RS.PA.060812-2.1,PA,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,"-1,94082700","-51,42111200",NaN,NaN,100% para EQUATORIAL PARï¿½ DISTRIBUIDORA DE E...,NaN,Portel - PA
12195,2022-11-01,Rosivaldo da Silva Coelho,57017,UFV.RS.PA.057017-6.1,PA,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,"-1,88246694","-50,91097000",NaN,NaN,100% para EQUATORIAL PARï¿½ DISTRIBUIDORA DE E...,NaN,Portel - PA
1085,2022-11-01,Santa Lúcia II,28395,PCH.PH.MT.028395-9.1,MT,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,7600,",00",Não,"-13,54433208","-59,03014799",2001-12-11,2031-12-11,100% para MAGGI Energia S.A. (PIE),17 - Tapajos,Sapezal - MT
5520,2022-11-01,Caetité F,37006,EOL.CV.BA.037006-1.1,BA,EOL,Construção,Eólica,Cinética do vento,Autorização,...,0,",00",Não,"-14,07535267","-42,52628322",2021-03-18,2056-03-18,100% para Eï¿½LICA CAETITï¿½ F S.A. (PIE),NaN,Caetité - BA
6683,2022-11-01,Haroldo Rodrigues Martins,39064,UFV.RS.PA.039064-0.1,PA,UFV,Operação,Solar,Radiação solar,Registro,...,1,",00",NaN,"-1,64193002","-52,31160000",NaN,NaN,100% para EQUATORIAL PARï¿½ DISTRIBUIDORA DE E...,NaN,Porto de Moz - PA
2013,2022-11-01,SMTE - Subestação Paracatu,29751,UTE.PE.MG.029751-8.1,MG,UTE,Operação,Fóssil,Petróleo,Registro,...,120,",00",Não,"-17,06861111","-47,11027778",NaN,NaN,100% para SERRA DA MESA TRANSMISSORA DE ENERGI...,NaN,Paracatu - MG